import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { ScopeProvider } from "./context/ScopeContext";
import { ThemeProvider } from "@/components/theme-provider";
import ConditionalHeader from "@/components/ConditionalHeader";

export const metadata: Metadata = {
  title: "BroadCast",
  description: "Generated by create redAntCompany",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen flex flex-col">
          <ScopeProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Toaster position="top-center" />
              <ConditionalHeader />
              <div className="bg-[#F4F2ED] flex-1 w-full">
                <main className="max-w-6xl mx-auto">{children}</main>
              </div>
            </ThemeProvider>
          </ScopeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
