import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Broadcast",
  description: "Generated by RedAnt",
   icons: {
    icon: "/logo/Broadcast.jpg",          // Favicon
    shortcut: "/logo/Broadcast.jpg",      // Shortcut icon
    apple: "/logo/Broadcast.jpg",         // Apple touch icon
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <ClerkProvider>
        <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
              >
          <html lang="en" suppressHydrationWarning>
            <body>{children}</body>
          </html>      
         </ThemeProvider>
  </ClerkProvider>

  )
}
