import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { ScopeProvider } from "./context/ScopeContext";
import { ThemeProvider } from "@/components/theme-provider";
import ConditionalHeader from "@/components/ConditionalHeader";

export const metadata: Metadata = {
  title: "BroadCast",
  description: "Generated by create redAntCompany",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen flex flex-col">
        <ClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ScopeProvider>
              <Toaster position="top-center" />
              
              <div>
                <ConditionalHeader />
                <main className="max-w-6xl mx-auto flex flex-col">
                  {children}
                </main>
              </div>
            </ScopeProvider>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
